site_name: Crow

# Repository
repo_name: CrowCpp/Crow
repo_url: https://github.com/CrowCpp/Crow
site_url: https://crowcpp.org
edit_uri: ""

theme: 
    name: material
    font: false
    language: 'en'
    features:
        navigation.tabs
    favicon: 'assets/favicon.svg'
    logo: 'assets/favicon.svg'
    icon:
        repo: fontawesome/brands/github-square
    static_templates:
        - privacy_policy.html
    custom_dir: docs/overrides

markdown_extensions:
    - admonition
    - pymdownx.highlight
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    
nav:
    - Home: index.md
    - Getting Started:
        - Setup:
            - Linux: getting_started/setup/linux.md
            - MacOS: getting_started/setup/macos.md
            - Windows: getting_started/setup/windows.md
            - Legacy: getting_started/setup/legacy.md
        - Your First Application: getting_started/your_first_application.md
    - Guides:
        - Different parts of Crow:
            - App: guides/app.md
            - Routes: guides/routes.md
            - Logging: guides/logging.md
            - JSON: guides/json.md
            - Templating (Mustache): guides/templating.md
            - Multipart: guides/multipart.md
            - Query Strings: guides/query-string.md
            - Middleware: guides/middleware.md
            - SSL: guides/ssl.md
            - Static Files: guides/static.md
            - Blueprints: guides/blueprints.md
            - Compression: guides/compression.md
            - Websockets: guides/websockets.md
            - Base64: guides/base64.md
            - Writing Tests: guides/testing.md
        - Using Crow:
            - HTTP Authorization: guides/auth.md
            - CORS Setup: guides/CORS.md
        - Server setup:
            - Proxies: guides/proxies.md
            - Systemd run on startup: guides/syste.md
    - API Reference:
        - API Reference: 'reference/index.html'
        
extra:
    analytics:
        provider: matomo
        id: 1
        link: //thee.dev/matomo/
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/crowcpp/crow
        - icon: fontawesome/brands/gitter
          link: https://gitter.im/crowfork/community

plugins:
    - redirects:
        redirect_maps:
            'getting_started/setup/': 'getting_started/setup/linux.md'
    - meta-descriptions

extra_css:
    - 'stylesheets/colors.css'
    - 'stylesheets/latofonts.css'
    - 'stylesheets/extra.css'

copyright: 'Copyright &copy; 2020-2022 CrowCpp'
